CREATE TYPE user_type AS ENUM ('USER', 'MERCHANT_USER', 'ADMIN', 'SUPER_ADMIN', 'SUPPORT_STAFF');
CREATE TYPE user_status AS ENUM ('ACTIVE', 'PENDING_VERIFY', 'LOCKED', 'BLOCKED', 'INACTIVE');

CREATE TYPE role_scope AS ENUM ('SYSTEM', 'MERCHANT');

CREATE TYPE wallet_status AS ENUM ('ACTIVE', 'LOCKED', 'CLOSED');
CREATE TYPE wallet_type AS ENUM ('PERSONAL');

CREATE TYPE ledger_transaction_type AS ENUM ('TOPUP', 'TRANSFER', 'PAYMENT', 'REFUND', 'WITHDRAWAL', 'ADJUSTMENT');
CREATE TYPE transaction_status AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'CANCELED');
CREATE TYPE ledger_entry_type AS ENUM ('DEBIT', 'CREDIT');
CREATE TYPE ledger_account_type AS ENUM ('USER_WALLET', 'MERCHANT_BALANCE', 'SYSTEM_ACCOUNT');

CREATE TYPE deposit_method AS ENUM ('SANDBOX_BANK', 'SANDBOX_CARD');
CREATE TYPE transfer_status AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'CANCELED');
CREATE TYPE deposit_status AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'CANCELED');
CREATE TYPE withdrawal_status AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'CANCELED');

CREATE TYPE merchant_status AS ENUM ('PENDING_REVIEW', 'ACTIVE', 'SUSPENDED', 'REJECTED', 'CLOSED');
CREATE TYPE business_type AS ENUM ('ONLINE', 'OFFLINE', 'BOTH');
CREATE TYPE api_key_status AS ENUM ('ACTIVE', 'REVOKED', 'EXPIRED');
CREATE TYPE api_environment AS ENUM ('SANDBOX', 'LIVE');

CREATE TYPE payment_order_status AS ENUM ('PENDING', 'PAID', 'EXPIRED', 'CANCELED', 'FAILED');
CREATE TYPE payment_transaction_status AS ENUM ('PENDING', 'SUCCESS', 'FAILED');
CREATE TYPE payment_refund_status AS ENUM ('NONE', 'PARTIALLY_REFUNDED', 'FULLY_REFUNDED');
CREATE TYPE qr_status AS ENUM ('ACTIVE', 'USED', 'EXPIRED', 'CANCELED');

CREATE TYPE refund_status AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'CANCELED');

CREATE TYPE webhook_event_type AS ENUM (
    'PAYMENT_SUCCESS',
    'PAYMENT_FAILED',
    'PAYMENT_EXPIRED',
    'PAYMENT_CANCELED',
    'REFUND_SUCCESS',
    'REFUND_FAILED'
);
CREATE TYPE webhook_status AS ENUM ('PENDING', 'SUCCESS', 'FAILED', 'RETRYING');

CREATE TYPE idempotency_actor_type AS ENUM ('USER', 'MERCHANT', 'ADMIN', 'SYSTEM');
CREATE TYPE idempotency_status AS ENUM ('PROCESSING', 'COMPLETED', 'FAILED');

CREATE TYPE log_level AS ENUM ('INFO', 'WARN', 'ERROR', 'CRITICAL');
CREATE TYPE audit_actor_type AS ENUM ('USER', 'MERCHANT', 'ADMIN', 'SYSTEM');

CREATE TYPE setting_value_type AS ENUM ('STRING', 'NUMBER', 'BOOLEAN', 'JSON');

CREATE TYPE public.group_funding_type AS ENUM (
    'SPLIT_BILL',
    'RED_PACKET'
);
